### PR TITLE
Fix/pr 605 fubinator fix google lighthouse passive event listeners

### LINKED ISSUE #581: Passive Event Listeners Google Lighthouse
**Describe the bug**
If you install the slider and run Google's Lighthouse, the error "Does not use passive listeners to improve scrolling performance" appears under "Best Practices" (see screenshot). This is probably caused by multiple event listeners.

**Expected behavior**
The message should not appear in a lighthouse report.

**Screenshots**
image

**Environment**

System:
    OS: Linux 5.7 Arch Linux
    CPU: (16) x64 AMD Ryzen 7 2700X Eight-Core Processor
    Memory: 1.77 GB / 15.63 GB
    Container: Yes
    Shell: 5.0.17 - /bin/bash
  Binaries:
    Node: 14.4.0 - /usr/bin/node
    Yarn: 1.22.4 - /usr/bin/yarn
    npm: 6.14.5 - /usr/bin/npm
  Browsers:
    Firefox: 77.0.1
  npmPackages:
    @brainhubeu/react-carousel: ^1.16.3 => 1.16.3

### PR DESCRIPTION
**Pull request by piotr-s-brainhub**
Deployed to https://beghp.github.io/gh-pages-rc-8<br>It fixes #581 <br><br>- [ ] an issue linked to the PR<br><br>

### CODE REVIEW

**Comment by brainhub-devops-2** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true">Warnings</th>
    </tr>
  </thead>
  <tbody><tr>
      <td>:warning:</td>
      <td>

  MODULE : node_modules/uglify-js/node_modules/wordwrap
 | LICENSE : MIT*
 | LICENSE_FILE : node_modules/uglify-js/node_modules/wordwrap/README.markdown
 | REPOSITORY: https://github.com/substack/node-wordwrap
 | PUBLISHER : James Halliday
 | EMAIL : mail@substack.net
 | URL : http://substack.net

  </td>
    </tr>
  
<tr>
      <td>:warning:</td>
      <td>

  MODULE : node_modules/vargs
 | LICENSE : MIT*
 | LICENSE_FILE : node_modules/vargs/LICENSE
 | REPOSITORY: undefined
 | PUBLISHER : Alexis Sellier
 | EMAIL : self@cloudhead.net
 | URL : undefined

  </td>
    </tr>
  
<tr>
      <td>:warning:</td>
      <td>

  MODULE : node_modules/gemini-coverage/node_modules/uglify-js
 | LICENSE : BSD*
 | LICENSE_FILE : node_modules/gemini-coverage/node_modules/uglify-js/LICENSE
 | REPOSITORY: https://github.com/mishoo/UglifyJS2
 | PUBLISHER : undefined
 | EMAIL : undefined
 | URL : undefined

  </td>
    </tr>
  
<tr>
      <td>:warning:</td>
      <td>

  MODULE : node_modules/trim
 | LICENSE : MIT*
 | LICENSE_FILE : node_modules/trim/Readme.md
 | REPOSITORY: undefined
 | PUBLISHER : TJ Holowaychuk
 | EMAIL : tj@vision-media.ca
 | URL : undefined

  </td>
    </tr>
  
<tr>
      <td>:warning:</td>
      <td>

  MODULE : node_modules/istanbul/node_modules/source-map
 | LICENSE : BSD
 | LICENSE_FILE : node_modules/istanbul/node_modules/source-map/LICENSE
 | REPOSITORY: https://github.com/mozilla/source-map
 | PUBLISHER : Nick Fitzgerald
 | EMAIL : nfitzgerald@mozilla.com
 | URL : undefined

  </td>
    </tr>
  
<tr>
      <td>:warning:</td>
      <td>

  MODULE : node_modules/gemini-coverage/node_modules/source-map
 | LICENSE : BSD
 | LICENSE_FILE : node_modules/gemini-coverage/node_modules/source-map/LICENSE
 | REPOSITORY: https://github.com/mozilla/source-map
 | PUBLISHER : Nick Fitzgerald
 | EMAIL : nfitzgerald@mozilla.com
 | URL : undefined

  </td>
    </tr>
  
<tr>
      <td>:warning:</td>
      <td>

  MODULE : node_modules/optimist
 | LICENSE : MIT*
 | LICENSE_FILE : node_modules/optimist/LICENSE
 | REPOSITORY: https://github.com/substack/node-optimist
 | PUBLISHER : James Halliday
 | EMAIL : mail@substack.net
 | URL : http://substack.net

  </td>
    </tr>
  
<tr>
      <td>:warning:</td>
      <td>

  MODULE : node_modules/map-stream
 | LICENSE : Custom: https://github.com/dominictarr/event-stream
 | LICENSE_FILE : node_modules/map-stream/LICENCE
 | REPOSITORY: https://github.com/dominictarr/map-stream
 | PUBLISHER : Dominic Tarr
 | EMAIL : dominic.tarr@gmail.com
 | URL : http://dominictarr.com

  </td>
    </tr>
  
<tr>
      <td>:warning:</td>
      <td>

  MODULE : node_modules/jsonify
 | LICENSE : Public Domain
 | LICENSE_FILE : node_modules/jsonify/README.markdown
 | REPOSITORY: https://github.com/substack/jsonify
 | PUBLISHER : Douglas Crockford
 | EMAIL : undefined
 | URL : http://crockford.com/

  </td>
    </tr>
  
<tr>
      <td>:warning:</td>
      <td>

  MODULE : node_modules/json-schema
 | LICENSE : AFLv2.1,BSD
 | LICENSE_FILE : node_modules/json-schema/README.md
 | REPOSITORY: https://github.com/kriszyp/json-schema
 | PUBLISHER : Kris Zyp
 | EMAIL : undefined
 | URL : undefined

  </td>
    </tr>
  
<tr>
      <td>:warning:</td>
      <td>

  MODULE : node_modules/indexof
 | LICENSE : MIT*
 | LICENSE_FILE : node_modules/indexof/Readme.md
 | REPOSITORY: undefined
 | PUBLISHER : undefined
 | EMAIL : undefined
 | URL : undefined

  </td>
    </tr>
  
<tr>
      <td>:warning:</td>
      <td>

  MODULE : node_modules/html
 | LICENSE : BSD*
 | LICENSE_FILE : node_modules/html/LICENSE
 | REPOSITORY: https://github.com/maxogden/commonjs-html-prettyprinter
 | PUBLISHER : Max Ogden
 | EMAIL : max@maxogden.com
 | URL : http://maxogden.com

  </td>
    </tr>
  
<tr>
      <td>:warning:</td>
      <td>

  MODULE : node_modules/glob-to-regexp
 | LICENSE : BSD*
 | LICENSE_FILE : node_modules/glob-to-regexp/README.md
 | REPOSITORY: https://github.com/fitzgen/glob-to-regexp
 | PUBLISHER : Nick Fitzgerald
 | EMAIL : fitzgen@gmail.com
 | URL : undefined

  </td>
    </tr>
  
<tr>
      <td>:warning:</td>
      <td>

  MODULE : node_modules/uglifyify/node_modules/extend
 | LICENSE : MIT*
 | LICENSE_FILE : node_modules/uglifyify/node_modules/extend/LICENSE
 | REPOSITORY: https://github.com/justmoon/node-extend
 | PUBLISHER : Stefan Thomas
 | EMAIL : justmoon@members.fsf.org
 | URL : http://www.justmoon.net

  </td>
    </tr>
  
<tr>
      <td>:warning:</td>
      <td>

  MODULE : node_modules/istanbul/node_modules/estraverse
 | LICENSE : BSD
 | LICENSE_FILE : node_modules/istanbul/node_modules/estraverse/LICENSE.BSD
 | REPOSITORY: https://github.com/estools/estraverse
 | PUBLISHER : undefined
 | EMAIL : undefined
 | URL : undefined

  </td>
    </tr>
  
<tr>
      <td>:warning:</td>
      <td>

  MODULE : node_modules/domutils
 | LICENSE : BSD*
 | LICENSE_FILE : node_modules/domutils/LICENSE
 | REPOSITORY: https://github.com/FB55/domutils
 | PUBLISHER : Felix Boehm
 | EMAIL : me@feedic.com
 | URL : undefined

  </td>
    </tr>
  
<tr>
      <td>:warning:</td>
      <td>

  MODULE : node_modules/eslint-plugin-import/node_modules/doctrine
 | LICENSE : BSD
 | LICENSE_FILE : node_modules/eslint-plugin-import/node_modules/doctrine/LICENSE.BSD
 | REPOSITORY: https://github.com/eslint/doctrine
 | PUBLISHER : undefined
 | EMAIL : undefined
 | URL : undefined

  </td>
    </tr>
  
<tr>
      <td>:warning:</td>
      <td>

  MODULE : node_modules/css-select
 | LICENSE : BSD*
 | LICENSE_FILE : node_modules/css-select/LICENSE
 | REPOSITORY: https://github.com/fb55/css-select
 | PUBLISHER : Felix Boehm
 | EMAIL : me@feedic.com
 | URL : undefined

  </td>
    </tr>
  
<tr>
      <td>:warning:</td>
      <td>

  MODULE : node_modules/parse-color/node_modules/color-convert
 | LICENSE : MIT*
 | LICENSE_FILE : node_modules/parse-color/node_modules/color-convert/LICENSE
 | REPOSITORY: https://github.com/harthur/color-convert
 | PUBLISHER : Heather Arthur
 | EMAIL : fayearthur@gmail.com
 | URL : undefined

  </td>
    </tr>
  
<tr>
      <td>:warning:</td>
      <td>

  MODULE : node_modules/async-foreach
 | LICENSE : MIT*
 | LICENSE_FILE : node_modules/async-foreach/LICENSE-MIT
 | REPOSITORY: https://github.com/cowboy/javascript-sync-async-foreach
 | PUBLISHER : "Cowboy" Ben Alman
 | EMAIL : undefined
 | URL : http://benalman.com/

  </td>
    </tr>
  </tbody>
</table>



<p align="right">
  Generated by :no_entry_sign: <a href="https://danger.systems/js">dangerJS</a> against bdfea77373c769dc6c8f94f5db0b4c12f61c4483
</p>

**Comment by RobertHebel** [comment]
In general, it works but on mouse events, I get an error in the console 
`
Unable to preventDefault inside passive event listener invocation.
`

@Fubinator could you take care of these errors?

**Comment by Fubinator** [comment]
@RobertHebel i've fixed it. I've pushed the change to my branch. I've removed the passive flag from the `mouseup` event listener, which seems to have caused the error. Lighthouse seems still fine with that as well.

**Comment by RobertHebel** [comment]
> @RobertHebel i've fixed it. I've pushed the change to my branch. I've removed the passive flag from the `mouseup` event listener, which seems to have caused the error. Lighthouse seems still fine with that as well.
> 
> e: Should I open another PR or are you already able to work with the new changes?

@Fubinator I merged changes from your branch. If everything will look ok, I will merge this PR

**Pull request merged**
