### PR TITLE
WIP: Project refactor

### PR DESCRIPTION
**Pull request by ghost**

### CODE REVIEW

**Comment by damian-brainhub** [comment]
bump! any update or progress on this? Is there anything we can help you with?

BTW Could you elaborate a bit about the purpose of this refactor?

**Comment by Robert-brainhub** [comment]
The purpose of this refactor was to delete files/ libraries that weren't used in this project. Also, I migrated test to jest.

I will try to move further with lib refactor at the end of the month

**Comment by piotr-s-brainhub** [comment]
@Robert-brainhub 

are you going to continue this work?

**Comment by piotr-s-brainhub** [comment]
As consulted with @RobertHebel , I close this PR.

**Pull request closed without merging**
