### PR TITLE
Fix/alucard17 fix 341 small offset doesnt give any effect

### LINKED ISSUE #341: small offset doesn't give any effect
[Issuehunt badges](https://issuehunt.io/r/brainhubeu/react-carousel/issues/341)

It is:
1) provide a small offset like `800`
2) nothing changes
3) provide a larger offset like `900`
4) the image is slightly moved

It should be:
2) the image should be moved by 800px
4) the image should be moved by 900px

video: https://recordit.co/gRhUQ6spo1

example code to paste in docs:
```
<Carousel
  arrows
  offset={800}
>
  <img src={imageOne} />
  <img src={imageTwo} />
  <img src={imageThree} />
</Carousel>
```

@brainhubeu/react-carousel version: 1.12.19
it occurs in docs

---

<details>
<summary>
<b>IssueHunt Summary</b>
</summary>

### Tips

- Checkout the [Issuehunt explorer](https://issuehunt.io/r/brainhubeu/react-carousel/) to discover more funded issues.
- Need some help from other developers? [Add your repositories](https://issuehunt.io/r/new) on IssueHunt to raise funds.
</details>

### PR DESCRIPTION
**Pull request by piotr-s-brainhub**
Deployed to https://beghp.github.io/gh-pages-rc-1<br>Fixes #341 <br>- [x] an issue linked to the PR<br><br><br><br><br>

### CODE REVIEW

**Comment by piotr-s-brainhub** [comment]
@Alucard17

I see `offset` moves a slide both horizontally and vertically but IMO it should move only in the slide movement direction (horizontal as default, vertical if the carousel is vertical though the vertical feature isn't finished yet).
However, to be frankly, I have to consult the `offset` behavior with the team.
Screenshot 2020-05-01 at 07 22 53

**Comment by piotr-s-brainhub** [comment]
@Alucard17 @karan-c3 

Are you going to fix this?

**Comment by Alucard17** [comment]
@piotr-s-brainhub okay I am working on it now.

**Comment by Alucard17** [comment]
hey @piotr-s-brainhub I was unable to update my code in this PR so I have updated the changes in following PR #489

**Comment by piotr-s-brainhub** [comment]
@Alucard17 

Now it works nice, thanks.
Screenshot 2020-05-15 at 22 29 12
Screenshot 2020-05-15 at 22 29 26
Screenshot 2020-05-15 at 22 29 33
Screenshot 2020-05-15 at 22 29 40
Screenshot 2020-05-15 at 22 29 47

However, I see some issues:
1) I'm not sure whether the offset is in pixels. It seems to be a bit larger.
2) For a large value and the infinite option, IMO it should work like it was scrolled manually by the same number of pixels but I see a blank space.
Screenshot 2020-05-15 at 22 31 01
3) When there's an offset, the infinite option set and I scroll very fast, the carousel disappears until I stop and white for a moment. Video: https://recordit.co/uJMEKQzJgM

**Comment by piotr-s-brainhub** [comment]
@Alucard17 

Are you going to fix these 3 issues?

**Comment by piotr-s-brainhub** [comment]
@Alucard17 ?

**Comment by RobertHebel** [comment]
I'm closing this PR because it's inactive for almost 2 months

**Pull request closed without merging**
