### PR TITLE
simulate mouse events

### LINKED ISSUE #47: breaks click and touch events
Hey there, It seems like the carousel globally prevents click/touch events for events outside (or inside the component). It'd also be nice if dragging had to be initiated inside the carousel so that scrolling didn't also move the slides

### PR DESCRIPTION
**Pull request by orangecms**
This is a fixup for https://github.com/brainhubeu/react-carousel/pull/61 to fix #47 :)

- [ ] `package.json:version` has been updated with `npm version patch` (or `major/minor` as appropriate)
- [ ] `@brainhubeu/react-carousel` version has been updated in `docs-www/package.json` to the same which is in `package.json:version`

### CODE REVIEW

**Comment by orangecms** [comment]
I've added JSdoc and fixed the code to make the linter happy :)

**Comment by orangecms** [comment]
Does that also mean that `onTouchMove` is no longer needed now btw?

**Comment by micabe** [comment]
Hello again, @mdrazyk @orangecms , after upgrading to `1.10.10s` still got this issue of outside carousel click not working and error message when I slide on a mobile device `[Intervention] Ignored attempt to cancel a touchmove event with cancelable=false, for example because scrolling is in progress and cannot be interrupted.`

**Comment by orangecms** [comment]
@micabe they probably forgot to rebuild before publishing the new version. In the repo, the `lib` directory hasn't changed.

**Comment by micabe** [comment]
@adam-golab I confirm `1.10.11` works great, thanks all for your hard work!

**Pull request merged**
