### PR TITLE
Fixed Carousel doesn't stop dragging when releasing the button outside of the container

### LINKED ISSUE #171: Carousel doesn't stop dragging when releasing the button outside of the container
[Issuehunt badges](https://issuehunt.io/r/brainhubeu/react-carousel/issues/171)

**Describe the bug**
Carousel doesn't stop dragging when `mouseup` event is triggered outside of carousel container.

**To Reproduce**
1. Go to https://brainhubeu.github.io/react-carousel/docs/examples/simpleUsage
2. Start dragging the carousel
3. While still pressing the button move the cursor outside of carousel container
4. Release the button
5. Notice carousel is still dragging while you're not pressing the button

**Expected behavior**
Carousel should stop dragging when releasing the button (no matter if it's in the container or not).

**Screenshots**
ezgif com-video-to-gif

**Desktop (please complete the following information):**
 - OS: [macOS 10.14.6]
 - Browser [Chrome]
 - Version [79.0.3945.88]

---

<details>
<summary>
<b>IssueHunt Summary</b>
</summary>

### Backers (Total: $5.00)

- [piotr-s-brainhub piotr-s-brainhub](https://issuehunt.io/u/piotr-s-brainhub) ($5.00)

### Tips

- Checkout the [Issuehunt explorer](https://issuehunt.io/r/brainhubeu/react-carousel/) to discover more funded issues.
- Need some help from other developers? [Add your repositories](https://issuehunt.io/r/new) on IssueHunt to raise funds.
---
IssueHunt has been backed by the following sponsors. [Become a sponsor](https://issuehunt.io/membership/members)
</details>

### PR DESCRIPTION
**Pull request by sinchang**
- [x] `package.json:version` has been updated with `npm version patch` (or `major/minor` as appropriate)
- [x] `@brainhubeu/react-carousel` version has been updated in `docs-www/package.json` to the same which is in `package.json:version`

btw: sort imports

Fixes #171

### CODE REVIEW

**Comment by Lukasz-pluszczewski** [comment]
This was very much needed! Thanks for fixing it.

BTW: I'm wondering why moving importing styles to the top?

**Comment by humbak** [comment]
We shouldn't agree on this import order change. It will be inconsistent with the rest of the components files.

**Comment by piotr-s-brainhub** [comment]
@humbak 

what do you think about adding this rule https://eslint.org/docs/rules/sort-imports in order to have a clearly defined imports order?

**Comment by sinchang** [comment]
I installed vscode plugin [Auto Import](https://marketplace.visualstudio.com/items?itemName=steoates.autoimport) on my machine, so it will sort imports automatically. if not good for us, I will revert the code.

**Comment by piotr-s-brainhub** [comment]
@sinchang 

you could revert so this PR would be OK for everybody and later we can figure out how we want to sort imports

**Comment by sinchang** [comment]
@piotr-s-brainhub done

**Pull request merged**
