### PR TITLE
Fix dot positions

### PR DESCRIPTION
**Pull request by 9GREG**
- [x] `package.json:version` has been updated with `npm version patch` (or `major/minor` as appropriate)
- [x] `@brainhubeu/react-carousel` version has been updated in `docs-www/package.json` to the same which is in `package.json:version`

---

<details>
<summary>
<b>IssueHunt Summary</b>
</summary>

### Referenced issues

This pull request has been submitted to:
- [#170: Bad positioning of dots](https://issuehunt.io/repos/116013398/issues/170)
---

IssueHunt has been backed by the following sponsors. [Become a sponsor](https://issuehunt.io/membership/members)
</details>

### CODE REVIEW

**Comment by piotr-s-brainhub** [comment]
Thanks for this PR.
I'm OK with that though I'm not sure whether it resolves the problem.
So we must test it and maybe get another review.

**Comment by 9GREG** [comment]
i've made another version changing only the css, but it broke when I resize the screen 😞

**Comment by piotr-s-brainhub** [comment]
@9GREG 

So this PR is fully working?
And another version (with nor PR submitted) broke?

**Comment by 9GREG** [comment]
@piotr-s-brainhub yes, this version is fully working and i'm using in a production app :D 
Later i'll try to fix with css only and open a new PR

**Comment by piotr-s-brainhub** [comment]
@iogreggg 

Can I ask you to fill in this form https://docs.google.com/forms/d/1tfRs1Io49tJBwz-06aDnz8hrJ3WySJTi45y4k6hHGaQ ?

**Pull request merged**
