### PR TITLE
Fix/arrow left right #106

### PR DESCRIPTION
**Pull request by udaypydi**
- [ ] `package.json:version` has been updated with `npm version patch` (or `major/minor` as appropriate)
- [ ] `@brainhubeu/react-carousel` version has been updated in `docs-www/package.json` to the same which is in `package.json:version`

### CODE REVIEW

**Comment by udaypydi** [comment]
@piotr-s-brainhub This fixes the right arrow issue.

**Comment by udaypydi** [comment]
@piotr-s-brainhub
How do we go about the custom arrows as they might contain default styling while being passed as a prop.

**Comment by piotr-s-brainhub** [comment]
@udaypydi 

IMO, for custom arrows, it would be good to provide `arrowLeftDisabled` and `arrowRightDisabled` options.

**Comment by piotr-s-brainhub** [comment]
@udaypydi 

If you want, to make that for custom arrows, you can open another PR.

**Pull request merged**
