### PR TITLE
Chawomack fix drag event listeners

### LINKED ISSUE #364: dragging eventListeners are still added to carousel when dragging is disabled
**Describe the bug**
The carousel adds eventListeners for dragging even when dragging is disabled on the carousel. This prevents functionality like being able to select text on the carouselItem and all the children within a carouselItem.

**To Reproduce**
1. Create a carousel of text elements with `draggable={false}`
2. Try to highlight/select the text in each carousel item
3. You cannot select the text because the eventListeners are preventing default behavior

**Expected behavior**
These event listeners should only be added to the carousel items when dragging is enabled on the carousel.

**Additional context**
I've forked the repository and fixed the issue here:
https://github.com/chawomack/react-carousel/commit/f8456fc96ae8e0e140799d9f3d1a182f3d22c8a6#diff-47f9a611545f9ac1e92bcfa0131e590b

### PR DESCRIPTION
**Pull request by piotr-s-brainhub**
Deployed to https://beghp.github.io/gh-pages-rc-5<br>It resolves #364 <br>- [ ] `package.json:version` has been updated with `npm version patch` (or `major/minor` as appropriate)<br>- [ ] `@brainhubeu/react-carousel` version has been updated in `docs-www/package.json` to the same which is in `package.json:version`<br><br>

### CODE REVIEW

**Comment by FinnGu** [comment]
@piotr-s-brainhub Do you want anyone specific to review this or is it ok if I test it, because this is exactly the feature missing in my project right now :D

**Comment by piotr-s-brainhub** [comment]
@FinnGu 

I checked it resolves the issue and doesn't break anything.
However, we need a review from someone from our organization to merge it.

**Comment by piotr-s-brainhub** [comment]
@cwomack @FinnGu 

I published this fix in @brainhubeu/react-carousel@1.13.12-alpha.0

**Comment by FinnGu** [comment]
@piotr-s-brainhub Ok, I thought that everyone could review this, as there is a link shown to me

**Pull request merged**
