### PR TITLE
Piotr szlagura active classname for every visible item

### LINKED ISSUE #313: Active classname for all visible elements
**Is your feature request related to a problem? Please describe.**
I'm not 100% sure if it's a feature request, bug or is it already possible with current version.

**Describe the solution you'd like**
Right now if `slidesPerPage > 1`, only one item gets className `BrainhubCarouselItem--active`. Is there a way to add this className to every currently visible element? Or something else, like `BrainhubCarouselItem--visible` etc...

**Describe alternatives you've considered**
I tried working around it by altering classnames of children passed down to carousel and calculating (or assuming) when they are visible, but I think it's mixing responsibilities, so I dropped this idea.

**Additional context**

Cały_ekran_10_03_2020__11_27

Thanks in advance for your help!

### PR DESCRIPTION
**Pull request by piotr-s-brainhub**
It resolves #313 
Deployed to https://beghp.github.io/gh-pages-rc-11<br><br>- [ ] `package.json:version` has been updated with `npm version patch` (or `major/minor` as appropriate)<br>- [ ] `@brainhubeu/react-carousel` version has been updated in `docs-www/package.json` to the same which is in `package.json:version`<br><br>

### CODE REVIEW

**Comment by piotr-s-brainhub** [comment]
@PiotrSzlagura

I see it's generally fixed but the first image, which is only partially shown, doesn't have the `BrainhubCarouselItem--visible` class.
Screenshot 2020-03-11 at 01 33 03


I'm not sure whether it should.
And what is your expectation?

**Comment by PiotrSzlagura** [comment]
@piotr-s-brainhub My goal was to add this className only to elements that are fully visible, but as I mentioned in my PR's description it could (and probably will) not work well with offset.

**Comment by piotr-s-brainhub** [comment]
I checked it works correctly - for each fully visible image, there's `BrainhubCarouselItem--visible` class.
Nothing is broken.

Regarding `offset`, we have already some problems with it (at least #341 ).

**Comment by humbak** [comment]
Not working in this scenario:

ezgif com-video-to-gif

**Comment by PiotrSzlagura** [comment]
@humbak You're right, I never tested it with `itemWidth` set. This is weird though, shouldn't there always be 2 items per page, even though smaller width allows more?

**Comment by RobertHebel** [comment]
@humbak Isn't that fault of itemWidth property which overrides slidesPerPage? I think in the scenario provided by you we should see 2 slides and appropriate offset around each slide, but instead of this we see multiple items

**Comment by humbak** [comment]
@PiotrSzlagura I focused more on `itemWidth` but I agree with you and @RobertHebel that we have here the second issue and that second is not connected to this feature.

**Comment by humbak** [comment]
Blocked because: We shouldn't merge it before `itemWidth` props will be also supported.

Nice to have: if it possible please add `--partially-visable` to items partially visabled

**Comment by PiotrSzlagura** [comment]
@humbak I think it's a good idea, though this PR is no longer mine and I'm not sure if I can make changes here

**Comment by piotr-s-brainhub** [comment]
@PiotrSzlagura 

in order to make changes, please open a PR from your fork to the main repo, `PiotrSzlagura-active-classname-for-every-visible-item` branch`

**Comment by RobertHebel** [comment]
Closing this branch and opening the new one with feature/ prefix

**Pull request closed without merging**
