### PR TITLE
WIP: Tab jump

### LINKED ISSUE #275: Tab jump over hidden elements
**Describe the bug**
Tabbing goes through hidden elements too.

**To Reproduce**
Use any >2 slides carousel with links. Try tabbing. Focus is running though hidden elements.

**Expected behavior**
Whole carousel should be recognized as few elements (in that order):
1) Arrows (if enabled) - obviously, left/right.
2) Dots (if enabled) - to enable selecting slide without jumping though all of those.
3) Whole carousel (should also be outlined to accent focus?) to enable keyboard left/right sliding)
4) Visible content elements - jumping though visible slide elements

**Additional context**
HTML's `tabindex` might be useful.
Well, this might be considered as both bug and feature 🤔 

* [ ] [Bug] Remove hidden elements `tabindex`.
* [ ] [Feature] Allow logical `tabindex` integration.

### PR DESCRIPTION
**Pull request by RobertHebel**
Deployed to https://beghp.github.io/gh-pages-rc-12<br>
Fixes #275 

Disable Tab jump over hidden elements<br>Tab Jump<br><br>- [ ] `package.json:version` has been updated with `npm version patch` (or `major/minor` as appropriate)<br>- [ ] `@brainhubeu/react-carousel` version has been updated in `docs-www/package.json` to the same which is in `package.json:version`<br><br>

### CODE REVIEW

**Comment by piotr-s-brainhub** [comment]
LGTM besides the failing build.
And in the future, I hope to have some regression tests for each bug fix.

**Comment by microbit-matt-hillsdon** [comment]
Just wanted to say that I hit the same issue (particularly problematic with the infinite option set) and this fix seems to work well for me in Edge/IE11/FF/Safari (I've only tested the carousel arrangement I use in practice).

**Comment by RobertHebel** [comment]
Yes it works, but I think it would be a good idea to wait until https://github.com/brainhubeu/react-carousel/pull/316 is merged and then reuse functions from that PR to detect which slides are visible/partially-visible and based on that make slide inert or not

**Comment by RobertHebel** [comment]
Closing and reopening with feature/ prefix

**Pull request closed without merging**
