### PR TITLE
Pr 231 microbit matt hillsdon build fix

### PR DESCRIPTION
**Pull request by piotr-s-brainhub**
Deployed to https://beghp.github.io/gh-pages-rc-6<br><br>- [ ] `package.json:version` has been updated with `npm version patch` (or `major/minor` as appropriate)<br>- [ ] `@brainhubeu/react-carousel` version has been updated in `docs-www/package.json` to the same which is in `package.json:version`<br><br>

### CODE REVIEW

**Comment by piotr-s-brainhub** [comment]
I checked it fixes the problem as the `yarn build` command returns 1 status in case of some problems:
```
⟩ yarn add --dev babel-loader
yarn add v1.16.0
warning ../../../package.json: No license field
[1/5] 🔍  Validating package.json...
[2/5] 🔍  Resolving packages...
[3/5] 🚚  Fetching packages...
[4/5] 🔗  Linking dependencies...
warning " > chai-enzyme@0.8.0" has unmet peer dependency "cheerio@0.19.x || 0.20.x || 0.22.x || 1.0.0-rc.1".
warning " > css-loader@3.4.2" has incorrect peer dependency "webpack@^4.0.0 || ^5.0.0".
warning " > extract-text-webpack-plugin@2.1.2" has incorrect peer dependency "webpack@^2.2.0".
warning " > file-loader@5.0.2" has incorrect peer dependency "webpack@^4.0.0 || ^5.0.0".
warning " > html-reporter@4.13.6" has unmet peer dependency "hermione@>=2.7.0".
warning " > style-loader@1.1.3" has incorrect peer dependency "webpack@^4.0.0 || ^5.0.0".
warning " > url-loader@3.0.0" has incorrect peer dependency "webpack@^4.0.0 || ^5.0.0".
warning " > babel-loader@8.0.6" has unmet peer dependency "@babel/core@^7.0.0".
[5/5] 🔨  Building fresh packages...
success Saved lockfile.
success Saved 3 new dependencies.
info Direct dependencies
└─ babel-loader@8.0.6
info All dependencies
├─ babel-loader@8.0.6
├─ find-cache-dir@2.1.0
└─ make-dir@2.1.0
✨  Done in 7.04s.

[piotr.sroczkowski@MacBook-Pro-user-2.local 20:18:43] ~/brainhub/open-source/react-carousel (pr-231-microbit-matt-hillsdon-build-fix ±)
⟩ yarn build
yarn run v1.16.0
warning ../../../package.json: No license field
$ npm run clean-dist
npm WARN lifecycle The node binary used for scripts is /var/folders/d4/9l3wz52s61l47yr26mnz8kcw0000gp/T/yarn--1581103152279-0.6687402284666277/node but npm is using /Users/piotr.sroczkowski/.nvm/versions/node/v12.5.0/bin/node itself. Use the `--scripts-prepend-node-path` option to include the path for the node binary npm was executed with.

> @brainhubeu/react-carousel@1.10.56 clean-dist /Users/piotr.sroczkowski/brainhub/open-source/react-carousel
> rimraf ./lib && mkdir lib

$ node tools/build.js
Generating minified bundle. This will take a moment...
(node:17448) DeprecationWarning: Chunk.modules is deprecated. Use Chunk.getNumberOfModules/mapModules/forEachModule/containsModule instead.
./src/index.js
Module build failed: Error: Plugin/Preset files are not allowed to export objects, only functions. In /Users/piotr.sroczkowski/brainhub/open-source/react-carousel/node_modules/babel-preset-react/lib/index.js
    at createDescriptor (/Users/piotr.sroczkowski/node_modules/@babel/core/lib/config/config-descriptors.js:178:11)
    at /Users/piotr.sroczkowski/node_modules/@babel/core/lib/config/config-descriptors.js:109:50
    at Array.map (<anonymous>)
    at createDescriptors (/Users/piotr.sroczkowski/node_modules/@babel/core/lib/config/config-descriptors.js:109:29)
    at createPresetDescriptors (/Users/piotr.sroczkowski/node_modules/@babel/core/lib/config/config-descriptors.js:101:10)
    at presets (/Users/piotr.sroczkowski/node_modules/@babel/core/lib/config/config-descriptors.js:47:19)
    at mergeChainOpts (/Users/piotr.sroczkowski/node_modules/@babel/core/lib/config/config-chain.js:320:26)
    at /Users/piotr.sroczkowski/node_modules/@babel/core/lib/config/config-chain.js:283:7
    at buildRootChain (/Users/piotr.sroczkowski/node_modules/@babel/core/lib/config/config-chain.js:120:22)
    at loadPrivatePartialConfig (/Users/piotr.sroczkowski/node_modules/@babel/core/lib/config/partial.js:85:55)
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

[piotr.sroczkowski@MacBook-Pro-user-2.local 20:19:14] ~/brainhub/open-source/react-carousel (pr-231-microbit-matt-hillsdon-build-fix ±)
⟩ echo $status
1

[piotr.sroczkowski@MacBook-Pro-user-2.local 20:20:39] ~/brainhub/open-source/react-carousel (pr-231-microbit-matt-hillsdon-build-fix ±)
⟩ git stash
Saved working directory and index state WIP on pr-231-microbit-matt-hillsdon-build-fix: cca4edf1 re-add yarn.lock

[piotr.sroczkowski@MacBook-Pro-user-2.local 20:20:45] ~/brainhub/open-source/react-carousel (pr-231-microbit-matt-hillsdon-build-fix)
⟩ git checkout master
Switched to branch 'master'
Your branch is up to date with 'origin/master'.

[piotr.sroczkowski@MacBook-Pro-user-2.local 20:20:50] ~/brainhub/open-source/react-carousel (master)
⟩ yarn build
yarn run v1.16.0
warning ../../../package.json: No license field
$ npm run clean-dist
npm WARN lifecycle The node binary used for scripts is /var/folders/d4/9l3wz52s61l47yr26mnz8kcw0000gp/T/yarn--1581103253055-0.7551157432096265/node but npm is using /Users/piotr.sroczkowski/.nvm/versions/node/v12.5.0/bin/node itself. Use the `--scripts-prepend-node-path` option to include the path for the node binary npm was executed with.

> @brainhubeu/react-carousel@1.10.56 clean-dist /Users/piotr.sroczkowski/brainhub/open-source/react-carousel
> rimraf ./lib && mkdir lib

$ node tools/build.js
Generating minified bundle. This will take a moment...
(node:17894) DeprecationWarning: Chunk.modules is deprecated. Use Chunk.getNumberOfModules/mapModules/forEachModule/containsModule instead.
Webpack stats: Hash: 299c2d71ab5a4cd087fa
Version: webpack 3.12.0
Time: 341ms
            Asset     Size  Chunks             Chunk Names
react-carousel.js  2.02 kB       0  [emitted]  main
   [0] ./src/index.js 1.25 kB {0} [built] [failed] [1 error]

ERROR in ./src/index.js
Module build failed: Error: Plugin/Preset files are not allowed to export objects, only functions. In /Users/piotr.sroczkowski/brainhub/open-source/react-carousel/node_modules/babel-preset-react/lib/index.js
    at createDescriptor (/Users/piotr.sroczkowski/node_modules/@babel/core/lib/config/config-descriptors.js:178:11)
    at /Users/piotr.sroczkowski/node_modules/@babel/core/lib/config/config-descriptors.js:109:50
    at Array.map (<anonymous>)
    at createDescriptors (/Users/piotr.sroczkowski/node_modules/@babel/core/lib/config/config-descriptors.js:109:29)
    at createPresetDescriptors (/Users/piotr.sroczkowski/node_modules/@babel/core/lib/config/config-descriptors.js:101:10)
    at presets (/Users/piotr.sroczkowski/node_modules/@babel/core/lib/config/config-descriptors.js:47:19)
    at mergeChainOpts (/Users/piotr.sroczkowski/node_modules/@babel/core/lib/config/config-chain.js:320:26)
    at /Users/piotr.sroczkowski/node_modules/@babel/core/lib/config/config-chain.js:283:7
    at buildRootChain (/Users/piotr.sroczkowski/node_modules/@babel/core/lib/config/config-chain.js:120:22)
    at loadPrivatePartialConfig (/Users/piotr.sroczkowski/node_modules/@babel/core/lib/config/partial.js:85:55)
Your app is compiled in production mode in /lib. It's ready to roll!
✨  Done in 2.36s.

[piotr.sroczkowski@MacBook-Pro-user-2.local 20:20:55] ~/brainhub/open-source/react-carousel (master)
⟩ echo $status
0
```

**Comment by piotr-s-brainhub** [comment]
I also checked all the demo/ docs examples are still working (for desktop).

**Comment by piotr-s-brainhub** [comment]
@microbit-matt-hillsdon thanks for contributing, we need a review from another maintainer to merge it

**Comment by piotr-s-brainhub** [comment]
@microbit-matt-hillsdon

Can I ask you to fill in this form https://docs.google.com/forms/d/1tfRs1Io49tJBwz-06aDnz8hrJ3WySJTi45y4k6hHGaQ ?

**Comment by microbit-matt-hillsdon** [comment]
> @microbit-matt-hillsdon
> 
> Can I ask you to fill in this form https://docs.google.com/forms/d/1tfRs1Io49tJBwz-06aDnz8hrJ3WySJTi45y4k6hHGaQ ?

Done. Thanks for integrating the changes.

**Pull request merged**
