### PR TITLE
BugFix: Addresses the trailing edge on StickyEdges

### PR DESCRIPTION
**Pull request by aayush420**
- [x] an issue linked to the PR

### CODE REVIEW

**Comment by RobertHebel** [comment]
@aayush420 could you resolve conflicts?

**Comment by aayush420** [comment]
> @aayush420 could you resolve conflicts?

@RobertHebel Conflict resolved..

**Comment by aayush420** [comment]
@RobertHebel Did you notice anything wrong with the commit?

**Comment by aayush420** [comment]
knock knock

**Pull request merged**
