### PR TITLE
[131] Fix/dont click on drag

### PR DESCRIPTION
**Pull request by CHaNGeTe**
+ Fixes https://github.com/brainhubeu/react-carousel/issues/131
+ makes clean-dist command windows compatible
+ exposes new prop to configure the min drag offset

- [x] `package.json:version` has been updated with `npm version patch` (or `major/minor` as appropriate)
- [x] `@brainhubeu/react-carousel` version has been updated in `docs-www/package.json` to the same which is in `package.json:version`

---

<details>
<summary>
<b>IssueHunt Summary</b>
</summary>

### Referenced issues

This pull request has been submitted to:
- [#131: Trigger click link when drag the carousel](https://issuehunt.io/repos/116013398/issues/131)
---

IssueHunt has been backed by the following sponsors. [Become a sponsor](https://issuehunt.io/membership/members)
</details>

### CODE REVIEW

**Comment by CHaNGeTe** [comment]
Ping @panacholn @johnatrevcontent

**Comment by piotr-s-brainhub** [comment]
Thanks @CHaNGeTe 

We need another review to merge.

**Comment by piotr-s-brainhub** [comment]
I created #212  instead of this PR because we need a branch in `brainhubeu` in order to check its deployment.

**Comment by piotr-s-brainhub** [comment]
I just validated it on https://brainhubeu.github.io/react-carousel and it's fixed.

**Pull request merged**
