### PR TITLE
Pr 245 udaypydi feature vertical orientation prop #162

### LINKED ISSUE #162: How to make carousel vertical?
Is there any possibility to make carousel vertical?

### PR DESCRIPTION
**Pull request by piotr-s-brainhub**
Deployed to https://beghp.github.io/gh-pages-rc-2<br>It fixes #162 <br><br>- [ ] `package.json:version` has been updated with `npm version patch` (or `major/minor` as appropriate)<br>- [ ] `@brainhubeu/react-carousel` version has been updated in `docs-www/package.json` to the same which is in `package.json:version`<br><br>

### CODE REVIEW

**Comment by udaypydi** [comment]
@piotr-s-brainhub I missed adding `vertical` in the other statement of vertical.md
Should I raise a PR for that?

**Comment by piotr-s-brainhub** [comment]
@udaypydi 

yes, you should open another PR to the `pr-245-udaypydi-feature-vertical_orientation_prop_#162` branch

**Comment by piotr-s-brainhub** [comment]
Thanks @udaypydi for this feature.

The basic stuff is working vertically but I found some issues:
1) `clickToChange` should show a part of the neighbor images enabling clicking them
```
<Carousel
  clickToChange
  slidesPerPage={2}
  centered
  vertical
>
 <img src={imageOne} />
 <img src={imageTwo} />
 <img src={imageThree} />
</Carousel>
```
Screenshot 2020-02-10 at 21 47 00

2) `slidesPerPage={2}` should show two full photos
```
<Carousel
  slidesPerPage={2}
  arrows
  infinite
  vertical
>
  <img src={imageOne} />
  <img src={imageTwo} />
  <img src={imageThree} />
</Carousel>
```
Screenshot 2020-02-10 at 21 48 10

3) `arrows` should show arrows but they aren't shown for `vertical` (the code and the screenshot from the previous example), also custom arrows aren't displayed

4) `vertical` with `dots` - when I place the cursor on the medium dot, it starts blinking (alternately `default` and `pointer`) and after going to the second slide, it's difficult to click another dot (sometimes it works and sometimes not)
```
<Carousel
  vertical
  dots
>
 <img src={imageOne} />
 <img src={imageTwo} />
 <img src={imageThree} />
</Carousel>
```
(the gif below doesn't show the reality because I saw alternate cursors)
http://g.recordit.co/1C11oDt3g9.gif

**Comment by udaypydi** [comment]
@piotr-s-brainhub Thanks for the update.

I think i messed it up somewhere with styles in documentation probably as I added a new class in `docs-www`. Will look into it.

**Comment by udaypydi** [comment]
@piotr-s-brainhub should the arrows be placed above and below respectively when the carousel is in the vertical mode?

**Comment by piotr-s-brainhub** [comment]
> @piotr-s-brainhub should the arrows be placed above and below respectively when the carousel is in the vertical mode?

@udaypydi I think so

**Comment by udaypydi** [comment]
@piotr-s-brainhub can you please help me in sorting this out? Seems like it's breaking in the `docs`. It works fine in other projects.

**Comment by piotr-s-brainhub** [comment]
@udaypydi 

could you paste same screenshots and example code from a project where it works correctly?

**Comment by udaypydi** [comment]
@piotr-s-brainhub 
image

The dots are breaking here as well. Can I know how the vertical carousel is supposed to look? So that I can debug into it much easily.

Thanks!

**Comment by piotr-s-brainhub** [comment]
@udaypydi 

IMO the vertical carousel should look in the following way:
1) a vertical carousel with arrows and dots:
carousel-vertical

2) a vertical carousel with arrows and thumbnails:
carousel-vertical-thumbnails

and please remember:
3) `slidesPerPage` param must work for vertical orientation as well
4) for `clickToChange`, no matter whether the carousel is horizontal or vertical, always a part of the neighbor images must be visible, allowing clicking them

**Comment by udaypydi** [comment]
@piotr-s-brainhub Thanks for the screenshots. Looks perfect. Will work on it.

**Comment by piotr-s-brainhub** [comment]
@udaypydi 

now, I see vertical dots are fixed, thanks but other examples still need to be fixed

**Comment by piotr-s-brainhub** [comment]
@udaypydi 

could you resolve conflicts?

**Comment by udaypydi** [comment]
@piotr-s-brainhub  Even this branch seems to be out of date with master. opened a new PR to master. 
#284

**Comment by piotr-s-brainhub** [comment]
I close this in favor of https://github.com/brainhubeu/react-carousel/pull/286

**Pull request closed without merging**
