### PR TITLE
Pr 197 danedavid issues remove deprecated lifecycle methods

### LINKED ISSUE #50: Remove deprecated method
[Issuehunt badges](https://issuehunt.io/r/brainhubeu/react-carousel/issues/50)

Library uses deprecated method (componentWillReceiveProps) to turn animation on and off (depending on the actual change of carousel value prop). We should implement it using e.g. getDerivedStateFromProps or some other method.

---

<details>
<summary>
<b>IssueHunt Summary</b>
</summary>

### Backers (Total: $5.00)

- [piotr-s-brainhub piotr-s-brainhub](https://issuehunt.io/u/piotr-s-brainhub) ($5.00)

### Submitted pull Requests
- [#197 Remove componentWillReceiveProps. Fixes #50.](https://issuehunt.io/r/brainhubeu/react-carousel/pull/197)
---

### Tips

- Checkout the [Issuehunt explorer](https://issuehunt.io/r/brainhubeu/react-carousel/) to discover more funded issues.
- Need some help from other developers? [Add your repositories](https://issuehunt.io/r/new) on IssueHunt to raise funds.
---
IssueHunt has been backed by the following sponsors. [Become a sponsor](https://issuehunt.io/membership/members)
</details>

### PR DESCRIPTION
**Pull request by piotr-s-brainhub**
Deployed to https://beghp.github.io/gh-pages-rc-1<br>
It fixes #50
<br>- [ ] `package.json:version` has been updated with `npm version patch` (or `major/minor` as appropriate)<br>- [ ] `@brainhubeu/react-carousel` version has been updated in `docs-www/package.json` to the same which is in `package.json:version`<br><br>

### CODE REVIEW

**Comment by piotr-s-brainhub** [comment]
I tested all the demo/ docs pages on desktop (Mac) and mobile (iPhone) and everything works.

**Comment by Lukasz-pluszczewski** [comment]
This PR breaks the infinite carousel behavior.
In https://beghp.github.io/gh-pages-rc-1/docs/examples/infinite, click left arrow when on first slide (carousel animates in the wrong direction). The same, incorrect behavior is seen when you're on "last" slide, and click right arrow.

That issue is exactly the reason why we did use deprecated lifecycle method. We didn't find the solution without componentWillReceiveProps.

**Comment by piotr-s-brainhub** [comment]
@danedavid 

could you open a PR, fixing the infinite issue into this branch (`pr-197-danedavid-issues-remove-deprecated-lifecycle-methods`)

**Comment by danedavid** [comment]
Hi @piotr-s-brainhub @Lukasz-pluszczewski 
Thanks for looking into my PR!
The code inside `componentWillReceiveProps` relies on too many instance methods like `getProp`, `clamp`, `checkIfValueChanged`, etc. which makes it difficult to move it to `static getDerivedStateFromProps`.

Can any of you please explain why, in the first place, we had to set the `infiniteTransitionFrom` state value when props change? I tried removing `getDerivedStateFromProps` and the above mentioned issue is fixed, and all unit tests are running. As for the regression tests, I'm not able to run them ( as there is no `npm run example` currently in npm scripts ). I tested all examples myself, and seems to work. Could you take a look at it? I've raised a PR https://github.com/brainhubeu/react-carousel/pull/233

**Comment by piotr-s-brainhub** [comment]
@danedavid 
I tested all the examples and they work correctly for me.

@Lukasz-pluszczewski 
Are you OK with the current code and the current working?

**Comment by piotr-s-brainhub** [comment]
@danedavid 

Can I ask you to fill in this form https://docs.google.com/forms/d/1tfRs1Io49tJBwz-06aDnz8hrJ3WySJTi45y4k6hHGaQ ?

**Comment by danedavid** [comment]
@piotr-s-brainhub Sure, done!

**Pull request merged**
